### ISSUE TITLE
Release: 2018.04.03

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#1150]
There are several bugs in the latest release. I think we should make a new minor release fixing these issues. The goal are the following:

Bug fixes:

- [x] Rework run-stats:
   - [x] Sharing intel_mp RX/TX counters does not seem to work properly on latest release #1137
   - [x] Snabb top interface view does not report RX/TX of non-master queue #1134
   - [x] The semantics of run_stats is changed in the latest lwAFTR release #1139
- [x] path_data.setter_for_grammar mangles path query containing #1116 
- [x] Minor snabb top UI improvements #1153
- [x] Binding-table generation always skip psid 0 #1155

Features:

None

There's a new Snabb release since our last lwAFTR release. I think we should not merge lastest Snabb release and focus only on fixing the bugs on the latest release.

**Comment by dpino** [comment]
Superseded by https://github.com/Igalia/snabb/issues/1174
