### ISSUE TITLE
Support incremental reconfiguration

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#562]
Right now in the `yang` branch we can statically configure an lwaftr process via a YANG-modelled configuration.  Great.  As part of this work we incorporated the binding table into the configuration, which is what our users expect; however, this removed the ability to reload just the binding table.  Indeed, the lwaftr no longer knows what file the configuration came from, so it can't do this on its own.

However the previous situation wasn't that great either.  You could reload the binding table, but you couldn't re-set the MTU or the next-hop IPv6 address or anything like that.  You just had to restart the application (which is fine enough of course).  But it would be nice to support more fine-grained reconfiguration.

So, that's what this bug is about: supporting reconfiguration of a running Snabb lwAFTR process that doesn't involve just restarting the whole thing.  First I wrote down a bit of design, then I see how the existing code works with this design and what's needed to get there.

## Design

The basic design is going to be that we will add an app to the graph: the *config app*.  The config app will have the configuration for the program as a whole.  When it is run by the engine, it will see if it has any incoming requests to change the program configuration.  If there are requests in the queue (more on this later), then the config app will determine what changes are needed and then apply those changes.

Notably, this process also happens on program startup as well.  The config app has a function which maps the global configuration (as an instance of the lwAFTR YANG schema) to an app graph.  On program startup (the first breath), the initial app graph is the empty set; so the config app compiles a list of requests to make of the engine (app instantiations, links, unlinks, removals, and updates; more on updates below) that will take the engine from the old state to the new, and then performs those requests.

In a multi-process setup (https://github.com/snabbco/snabb/pull/1021) the change requests can be shipped over a back-channel from the main process where the config app runs, to the worker processes 
where the changes are applied.  In a single-process setup the changes can be applied directly.

Manipulating the app graph is necessary for when (for example) you decide to add an ingress filter but you don't have a pflua app instantiated and linked.  However there are also other changes you might want that involve a configuration change in an existing app.  In general, the process of taking app configuration A and transforming it to app configuration A* can compile to an unlinking of that app, tearing it down, reinstantiating it, and relinking it.

However in some cases we can avoid this somewhat heavyweight operation.  In particular for the lwAFTR, a change from config A to A* where the only difference is in the binding table can proceed by just calling a method on the lwaftr.  So we will provide, for certain app types, the ability to compile some changes as method calls on apps.

## Current status

The lwAFTR and a number of other apps already have a function that maps a configuration to an app graph; in the lwaftr it's in `program/lwaftr/setup.lua`.  So everything that we have to implement is generic except the bit that specializes compilation of lwaftr configuration changes.

The Snabb engine already implements a form of state tracking and change compilation -- see `compute_config_actions` and `apply_config_actions` in `core.app`.  So we just have to make it so that instead of the actions being applied in the main process, we apply them in the worker (in a multi-process scenario); and we need to handle `reconfig` in a more fine-grained way.  Currently `compute_config_actions` does a full `lib.equal` comparison to see whether two configs are the same (and thus to know whether to reconfig or keep an existing app), and that's not a good strategy for the binding table.

The current state of the actions applier thing also has the problem that `compute_config_actions` makes a changeset that is O(n) in the size of the graph, instead of O(n) in the size of the change.  This is because the actions effectively copy the old graph to the new graph instead of mutating the graph in place.  And, `apply_config_actions` has a lot of internal logic as well.  I think probably this pair of routines should do more compilation, such that `apply_config_actions` has less work to do and never has to check whether a step in its work plan is valid or not.  (cc @eugeneia and @lukego on this point)

To update a binding table entry, the reconfig application should probably just recognize change requests that can happen by a direct update on part of a YANG configuration.  In that case the manager process updates its config appropriately and issues a similar change request to the worker processes.

## Implementation plan

- [x] Make a config app that takes a schema name, a configuration file name (or a configuration object), and a function from configuration->app-graph, and arrange for it to populate the app graph on first breath.  (Confusingly, the low-level app graph concept is called a "configuration" also in snabb :/)

- [x] Optimize core Snabb reconfiguration to minimize change lists.

- [ ] Merge in the multiprocess work from https://github.com/snabbco/snabb/pull/1021 and separate the worker from the config app.  Probably we need to make an additional app in the worker to listen for change lists and apply them.  How to communicate big changes though?  Probably this backchannel needs to be a ring buffer mapped into both address spaces like the `apps.lwaftr.channel` but it needs a side storage area for arbitrary-sized configurations like the binding table.

Maybe we can compile each app configuration to a binary file, using the yang binary compiler, and then store them named SHA256.conf in the group directory where SHA256 is the hash of the binary?  At least that way we can know when big configurations change, which would be nice.  We'd need a way to serialize generic configurations though.  Perhaps Snabb apps could indicate their YANG model (for the app) and if not given you could get a "generic yang model" which has Lua data in some string representation that can be eval'd.  Dunno, an open question here.

- [x] Make "snabb config" app listen to a UNIX socket or something for change requests.  One command on this socket should be "reload your configuration".  Another could be "get your configuration" which would print out the program configuration using the YANG schema.  Obviously this is not appropriate for running in the data plane at this point -- we need to be in a multiprocess world here.

**Comment by wingo** [comment]
Thinking about it more, there are two cases.  One is where you are just told to reload your configuration.  There, the protocol in the core will work well enough for us, especially after the recent optimizations in SnabbCo#1067.  The other is when you are told to make a change -- like "set external-interface.ip = 1.2.3.4" or something.  In that second case there are two sub-cases :)  One is the generic one: you update your configuration directly, rerun your setup function to get an app graph, compute configuration actions that will take worker state from old to new, then apply the changes.  As before.  The other one is where you are able to know, given the small change, a corresponding small change to make to specific apps in the data plane.  This is domain-specific knowledge.  An example of this second case would be "add this binding table entry".

To implement this we should add a routine to the YANG schema support module that takes a change and compiles it to a special action type somehow that will result on a method being called on the app,or something like that.

**Comment by mwiget** [comment]
@wingo: I like the concept of a config/setup app as part of a graph. Works well with the single threaded nature and leaves it up to each app to do the "right" thing if required. 
Looking at your current work with lwaftr, merging binding table and configuration into one file, do you see lwaftr knowing how to act on a configuration change that goes beyond a simple value change? Like e.g. changing the graph by adding / removing apps? 
Right now I have some intelligence in the control app for snabb, which signals a binding table change to snabb or restarts snabb. With a single configuration file this becomes a bit more complex, but I can see snabb config app taking ownership of such a decision.

**Comment by wingo** [comment]
@mwiget Interestingly I think snabb should handle non-simple changes well.  The special case is where you can just change one value, and we're currently working on a good solution for that, but it's been possible for a while to reconfigure the graph as a whole.  See paragraph 3 under current status and https://github.com/snabbco/snabb/issues/1067 for the core code.

**Comment by wingo** [comment]
Done via #576.
